# Generated by Django 3.1.1 on 2020-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=60)),
                ('pin_code', models.CharField(default='', max_length=10)),
                ('mobile_1', models.CharField(default='', max_length=15)),
                ('mobile_2', models.CharField(default='', max_length=15)),
                ('time_am', models.CharField(default='', max_length=5)),
                ('time_pm', models.CharField(default='', max_length=5)),
                ('mobile_job_1', models.CharField(default='', max_length=15)),
                ('mobile_job_2', models.CharField(default='', max_length=15)),
                ('time_job_am', models.CharField(default='', max_length=5)),
                ('time_job_pm', models.CharField(default='', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
