# Generated by Django 3.1.1 on 2020-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
