# Generated by Django 3.1.1 on 2020-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20201107_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
