# Generated by Django 3.1.1 on 2020-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20201107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_events',
            name='short_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
