# Generated by Django 3.1.1 on 2020-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_auto_20201107_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='review',
            field=models.CharField(max_length=250),
        ),
    ]
