# Generated by Django 3.1.1 on 2020-11-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20201108_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ('-updated',), 'verbose_name_plural': 'Testimonials'},
        ),
    ]
